### ISSUE TITLE
Back Button After Editing Listing

### ISSUE THREAD

**Issue by Torboto** [gcoomber/TextCrunch#98] opened 2015-04-06 10:43 UTC
Shouldn't be able to go back through the stack after editing a listing. Instead of putting another screen on the stack to view the updated Listing, perhaps we can just reload the previous ListingView screen (go back, I suppose).

**Comment by hpabst** [comment] 2015-04-06 14:35
This is a duplicate of issue #69.

**Closed by hpabst** 2015-04-06 14:35 UTC
